# Generated by Django 3.1.2 on 2020-10-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olamundo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='function',
            new_name='Funcionario',
        ),
    ]
